name: Agent Manager RC

on:
  push:
    branches: [ "rc" ]
    paths:
      - 'agent-manager/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: agent-manager
      environment: v10-rc
      directory: agent-manager
      binary: server
      branch: rc
