name: Mutate RC

on:
  push:
    branches: [ "rc" ]
    paths:
      - 'mutate/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-basic.yml
    with:
      image_name: mutate
      environment: v10-rc
      directory: mutate
      branch: rc