name: Mutate QA

on:
  pull_request:
    branches: [ "rc" ]
    paths:
      - 'mutate/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-basic.yml
    with:
      image_name: mutate
      environment: v10-qa
      directory: mutate
      branch: main