name: O365 Release

on:
  push:
    tags: [ 'v*' ]
    paths:
      - 'office365/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-golang.yml
    with:
      image_name: office365
      environment: v10
      directory: office365
      binary: o365_integration
      branch: rc