name: Mutate Release

on:
  push:
    tags: [ 'v*' ]
    paths:
      - 'mutate/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-basic.yml
    with:
      image_name: mutate
      environment: v10
      directory: mutate
      branch: rc