name: User Auditor Dev
on:
  push:
    branches: [ main ]
    paths:
      - 'user-auditor/**'
  workflow_dispatch:
jobs:
  docker-native-image-java:
    uses: ./.github/workflows/docker-graalvm.yml
    with:
      image_name: user-auditor
      environment: v10-dev
      directory: user-auditor
