name: Web PDF RC
on:
  push:
    branches: [ "rc" ]
    paths:
      - 'web-pdf/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: web-pdf
      environment: v10-rc
      directory: web-pdf
      branch: rc
