name: Web PDF QA
on:
  pull_request:
    branches: [ "rc" ]
    paths:
      - 'web-pdf/**'

jobs:
  docker:
    uses: ./.github/workflows/docker-java.yml
    with:
      image_name: web-pdf
      environment: v10-qa
      directory: web-pdf
      branch: main
